// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED    PluginType = 0
	PluginType_PLUGIN_TYPE_AUTH           PluginType = 1
	PluginType_PLUGIN_TYPE_SCORING        PluginType = 2
	PluginType_PLUGIN_TYPE_NOTIFICATION   PluginType = 3
	PluginType_PLUGIN_TYPE_CHALLENGE_TYPE PluginType = 4
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_UNSPECIFIED",
		1: "PLUGIN_TYPE_AUTH",
		2: "PLUGIN_TYPE_SCORING",
		3: "PLUGIN_TYPE_NOTIFICATION",
		4: "PLUGIN_TYPE_CHALLENGE_TYPE",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED":    0,
		"PLUGIN_TYPE_AUTH":           1,
		"PLUGIN_TYPE_SCORING":        2,
		"PLUGIN_TYPE_NOTIFICATION":   3,
		"PLUGIN_TYPE_CHALLENGE_TYPE": 4,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// Info is served by every plugin and read at load time.
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // must match the manifest name
	Type          PluginType             `protobuf:"varint,2,opt,name=type,proto3,enum=osctf.plugin.v1.PluginType" json:"type,omitempty"`
	Abi           string                 `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`                   // "1.<minor>"
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`           // the plugin's own semver, for display
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // optional feature flags within the type (e.g. "password")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func (x *InfoResponse) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type AuthenticateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Identifier string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Plaintext credential the user submitted FOR THIS PROVIDER (password capability only).
	// Never the OSCTF password, a hash, or a token. See the trust model.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *AuthenticateRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type BeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUri   string                 `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *BeginRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type BeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorizeUrl  string                 `protobuf:"bytes,1,opt,name=authorize_url,json=authorizeUrl,proto3" json:"authorize_url,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginResponse) Reset() {
	*x = BeginResponse{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResponse) ProtoMessage() {}

func (x *BeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResponse.ProtoReflect.Descriptor instead.
func (*BeginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *BeginResponse) GetAuthorizeUrl() string {
	if x != nil {
		return x.AuthorizeUrl
	}
	return ""
}

func (x *BeginResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // callback query params
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CompleteRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// The external identity the plugin vouches for. `email` is the plugin's OUTPUT (its knowledge
// of the subject, for host-side provisioning) — not host-provided PII. The host maps
// subject -> local user, then issues its OWN session.
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"` // stable IdP-unique id
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"` // suggested handle
	Claims        map[string]string      `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Identity) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initial       int32                  `protobuf:"varint,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Min           int32                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Decay         int32                  `protobuf:"varint,3,opt,name=decay,proto3" json:"decay,omitempty"`
	Solves        int32                  `protobuf:"varint,4,opt,name=solves,proto3" json:"solves,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // extra curve knobs, from config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ScoreRequest) GetInitial() int32 {
	if x != nil {
		return x.Initial
	}
	return 0
}

func (x *ScoreRequest) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ScoreRequest) GetDecay() int32 {
	if x != nil {
		return x.Decay
	}
	return 0
}

func (x *ScoreRequest) GetSolves() int32 {
	if x != nil {
		return x.Solves
	}
	return 0
}

func (x *ScoreRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ScoreResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SubscriptionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventNames    []string               `protobuf:"bytes,1,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionList) Reset() {
	*x = SubscriptionList{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionList) ProtoMessage() {}

func (x *SubscriptionList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionList.ProtoReflect.Descriptor instead.
func (*SubscriptionList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionList) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                           // "challenge.solved"
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                               // unique event id (dedup)
	OccurredAt    string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`                                             // RFC3339
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // flat, non-secret AND non-PII
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type NotifyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyAck) Reset() {
	*x = NotifyAck{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyAck) ProtoMessage() {}

func (x *NotifyAck) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyAck.ProtoReflect.Descriptor instead.
func (*NotifyAck) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyAck) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	FieldErrors   map[string]string      `protobuf:"bytes,2,rep,name=field_errors,json=fieldErrors,proto3" json:"field_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Normalized    map[string]string      `protobuf:"bytes,3,rep,name=normalized,proto3" json:"normalized,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetFieldErrors() map[string]string {
	if x != nil {
		return x.FieldErrors
	}
	return nil
}

func (x *ValidateResponse) GetNormalized() map[string]string {
	if x != nil {
		return x.Normalized
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submitted     string                 `protobuf:"bytes,1,opt,name=submitted,proto3" json:"submitted,omitempty"`                                                                         // the user's guess (never the flag)
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // author config (host injects no flag)
	Instance      map[string]string      `protobuf:"bytes,3,rep,name=instance,proto3" json:"instance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // per-instance metadata (no flag)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *CheckRequest) GetSubmitted() string {
	if x != nil {
		return x.Submitted
	}
	return ""
}

func (x *CheckRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CheckRequest) GetInstance() map[string]string {
	if x != nil {
		return x.Instance
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correct       bool                   `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *CheckResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x0fosctf.plugin.v1\"\r\n" +
	"\vInfoRequest\"\xa3\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.osctf.plugin.v1.PluginTypeR\x04type\x12\x10\n" +
	"\x03abi\x18\x03 \x01(\tR\x03abi\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"M\n" +
	"\x13AuthenticateRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"1\n" +
	"\fBeginRequest\x12!\n" +
	"\fredirect_uri\x18\x01 \x01(\tR\vredirectUri\"J\n" +
	"\rBeginResponse\x12#\n" +
	"\rauthorize_url\x18\x01 \x01(\tR\fauthorizeUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xa8\x01\n" +
	"\x0fCompleteRequest\x12D\n" +
	"\x06params\x18\x01 \x03(\v2,.osctf.plugin.v1.CompleteRequest.ParamsEntryR\x06params\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\bIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12=\n" +
	"\x06claims\x18\x04 \x03(\v2%.osctf.plugin.v1.Identity.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\fScoreRequest\x12\x18\n" +
	"\ainitial\x18\x01 \x01(\x05R\ainitial\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\x12\x14\n" +
	"\x05decay\x18\x03 \x01(\x05R\x05decay\x12\x16\n" +
	"\x06solves\x18\x04 \x01(\x05R\x06solves\x12A\n" +
	"\x06params\x18\x05 \x03(\v2).osctf.plugin.v1.ScoreRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\rScoreResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"3\n" +
	"\x10SubscriptionList\x12\x1f\n" +
	"\vevent_names\x18\x01 \x03(\tR\n" +
	"eventNames\"\xbb\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x124\n" +
	"\x04data\x18\x04 \x03(\v2 .osctf.plugin.v1.Event.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\tNotifyAck\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\"\x92\x01\n" +
	"\x0fValidateRequest\x12D\n" +
	"\x06config\x18\x01 \x03(\v2,.osctf.plugin.v1.ValidateRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x02\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12U\n" +
	"\ffield_errors\x18\x02 \x03(\v22.osctf.plugin.v1.ValidateResponse.FieldErrorsEntryR\vfieldErrors\x12Q\n" +
	"\n" +
	"normalized\x18\x03 \x03(\v21.osctf.plugin.v1.ValidateResponse.NormalizedEntryR\n" +
	"normalized\x1a>\n" +
	"\x10FieldErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fNormalizedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x02\n" +
	"\fCheckRequest\x12\x1c\n" +
	"\tsubmitted\x18\x01 \x01(\tR\tsubmitted\x12A\n" +
	"\x06config\x18\x02 \x03(\v2).osctf.plugin.v1.CheckRequest.ConfigEntryR\x06config\x12G\n" +
	"\binstance\x18\x03 \x03(\v2+.osctf.plugin.v1.CheckRequest.InstanceEntryR\binstance\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rInstanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\acorrect\x18\x01 \x01(\bR\acorrect*\x96\x01\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PLUGIN_TYPE_AUTH\x10\x01\x12\x17\n" +
	"\x13PLUGIN_TYPE_SCORING\x10\x02\x12\x1c\n" +
	"\x18PLUGIN_TYPE_NOTIFICATION\x10\x03\x12\x1e\n" +
	"\x1aPLUGIN_TYPE_CHALLENGE_TYPE\x10\x042\xad\x02\n" +
	"\x04Auth\x12C\n" +
	"\x04Info\x12\x1c.osctf.plugin.v1.InfoRequest\x1a\x1d.osctf.plugin.v1.InfoResponse\x12O\n" +
	"\fAuthenticate\x12$.osctf.plugin.v1.AuthenticateRequest\x1a\x19.osctf.plugin.v1.Identity\x12F\n" +
	"\x05Begin\x12\x1d.osctf.plugin.v1.BeginRequest\x1a\x1e.osctf.plugin.v1.BeginResponse\x12G\n" +
	"\bComplete\x12 .osctf.plugin.v1.CompleteRequest\x1a\x19.osctf.plugin.v1.Identity2\x96\x01\n" +
	"\aScoring\x12C\n" +
	"\x04Info\x12\x1c.osctf.plugin.v1.InfoRequest\x1a\x1d.osctf.plugin.v1.InfoResponse\x12F\n" +
	"\x05Value\x12\x1d.osctf.plugin.v1.ScoreRequest\x1a\x1e.osctf.plugin.v1.ScoreResponse2\xe3\x01\n" +
	"\fNotification\x12C\n" +
	"\x04Info\x12\x1c.osctf.plugin.v1.InfoRequest\x1a\x1d.osctf.plugin.v1.InfoResponse\x12P\n" +
	"\rSubscriptions\x12\x1c.osctf.plugin.v1.InfoRequest\x1a!.osctf.plugin.v1.SubscriptionList\x12<\n" +
	"\x06Notify\x12\x16.osctf.plugin.v1.Event\x1a\x1a.osctf.plugin.v1.NotifyAck2\xf7\x01\n" +
	"\rChallengeType\x12C\n" +
	"\x04Info\x12\x1c.osctf.plugin.v1.InfoRequest\x1a\x1d.osctf.plugin.v1.InfoResponse\x12U\n" +
	"\x0eValidateConfig\x12 .osctf.plugin.v1.ValidateRequest\x1a!.osctf.plugin.v1.ValidateResponse\x12J\n" +
	"\tCheckFlag\x12\x1d.osctf.plugin.v1.CheckRequest\x1a\x1e.osctf.plugin.v1.CheckResponseB=Z;github.com/osctf/platform/internal/plugin/pluginpb;pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_plugin_proto_goTypes = []any{
	(PluginType)(0),             // 0: osctf.plugin.v1.PluginType
	(*InfoRequest)(nil),         // 1: osctf.plugin.v1.InfoRequest
	(*InfoResponse)(nil),        // 2: osctf.plugin.v1.InfoResponse
	(*AuthenticateRequest)(nil), // 3: osctf.plugin.v1.AuthenticateRequest
	(*BeginRequest)(nil),        // 4: osctf.plugin.v1.BeginRequest
	(*BeginResponse)(nil),       // 5: osctf.plugin.v1.BeginResponse
	(*CompleteRequest)(nil),     // 6: osctf.plugin.v1.CompleteRequest
	(*Identity)(nil),            // 7: osctf.plugin.v1.Identity
	(*ScoreRequest)(nil),        // 8: osctf.plugin.v1.ScoreRequest
	(*ScoreResponse)(nil),       // 9: osctf.plugin.v1.ScoreResponse
	(*SubscriptionList)(nil),    // 10: osctf.plugin.v1.SubscriptionList
	(*Event)(nil),               // 11: osctf.plugin.v1.Event
	(*NotifyAck)(nil),           // 12: osctf.plugin.v1.NotifyAck
	(*ValidateRequest)(nil),     // 13: osctf.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil),    // 14: osctf.plugin.v1.ValidateResponse
	(*CheckRequest)(nil),        // 15: osctf.plugin.v1.CheckRequest
	(*CheckResponse)(nil),       // 16: osctf.plugin.v1.CheckResponse
	nil,                         // 17: osctf.plugin.v1.CompleteRequest.ParamsEntry
	nil,                         // 18: osctf.plugin.v1.Identity.ClaimsEntry
	nil,                         // 19: osctf.plugin.v1.ScoreRequest.ParamsEntry
	nil,                         // 20: osctf.plugin.v1.Event.DataEntry
	nil,                         // 21: osctf.plugin.v1.ValidateRequest.ConfigEntry
	nil,                         // 22: osctf.plugin.v1.ValidateResponse.FieldErrorsEntry
	nil,                         // 23: osctf.plugin.v1.ValidateResponse.NormalizedEntry
	nil,                         // 24: osctf.plugin.v1.CheckRequest.ConfigEntry
	nil,                         // 25: osctf.plugin.v1.CheckRequest.InstanceEntry
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: osctf.plugin.v1.InfoResponse.type:type_name -> osctf.plugin.v1.PluginType
	17, // 1: osctf.plugin.v1.CompleteRequest.params:type_name -> osctf.plugin.v1.CompleteRequest.ParamsEntry
	18, // 2: osctf.plugin.v1.Identity.claims:type_name -> osctf.plugin.v1.Identity.ClaimsEntry
	19, // 3: osctf.plugin.v1.ScoreRequest.params:type_name -> osctf.plugin.v1.ScoreRequest.ParamsEntry
	20, // 4: osctf.plugin.v1.Event.data:type_name -> osctf.plugin.v1.Event.DataEntry
	21, // 5: osctf.plugin.v1.ValidateRequest.config:type_name -> osctf.plugin.v1.ValidateRequest.ConfigEntry
	22, // 6: osctf.plugin.v1.ValidateResponse.field_errors:type_name -> osctf.plugin.v1.ValidateResponse.FieldErrorsEntry
	23, // 7: osctf.plugin.v1.ValidateResponse.normalized:type_name -> osctf.plugin.v1.ValidateResponse.NormalizedEntry
	24, // 8: osctf.plugin.v1.CheckRequest.config:type_name -> osctf.plugin.v1.CheckRequest.ConfigEntry
	25, // 9: osctf.plugin.v1.CheckRequest.instance:type_name -> osctf.plugin.v1.CheckRequest.InstanceEntry
	1,  // 10: osctf.plugin.v1.Auth.Info:input_type -> osctf.plugin.v1.InfoRequest
	3,  // 11: osctf.plugin.v1.Auth.Authenticate:input_type -> osctf.plugin.v1.AuthenticateRequest
	4,  // 12: osctf.plugin.v1.Auth.Begin:input_type -> osctf.plugin.v1.BeginRequest
	6,  // 13: osctf.plugin.v1.Auth.Complete:input_type -> osctf.plugin.v1.CompleteRequest
	1,  // 14: osctf.plugin.v1.Scoring.Info:input_type -> osctf.plugin.v1.InfoRequest
	8,  // 15: osctf.plugin.v1.Scoring.Value:input_type -> osctf.plugin.v1.ScoreRequest
	1,  // 16: osctf.plugin.v1.Notification.Info:input_type -> osctf.plugin.v1.InfoRequest
	1,  // 17: osctf.plugin.v1.Notification.Subscriptions:input_type -> osctf.plugin.v1.InfoRequest
	11, // 18: osctf.plugin.v1.Notification.Notify:input_type -> osctf.plugin.v1.Event
	1,  // 19: osctf.plugin.v1.ChallengeType.Info:input_type -> osctf.plugin.v1.InfoRequest
	13, // 20: osctf.plugin.v1.ChallengeType.ValidateConfig:input_type -> osctf.plugin.v1.ValidateRequest
	15, // 21: osctf.plugin.v1.ChallengeType.CheckFlag:input_type -> osctf.plugin.v1.CheckRequest
	2,  // 22: osctf.plugin.v1.Auth.Info:output_type -> osctf.plugin.v1.InfoResponse
	7,  // 23: osctf.plugin.v1.Auth.Authenticate:output_type -> osctf.plugin.v1.Identity
	5,  // 24: osctf.plugin.v1.Auth.Begin:output_type -> osctf.plugin.v1.BeginResponse
	7,  // 25: osctf.plugin.v1.Auth.Complete:output_type -> osctf.plugin.v1.Identity
	2,  // 26: osctf.plugin.v1.Scoring.Info:output_type -> osctf.plugin.v1.InfoResponse
	9,  // 27: osctf.plugin.v1.Scoring.Value:output_type -> osctf.plugin.v1.ScoreResponse
	2,  // 28: osctf.plugin.v1.Notification.Info:output_type -> osctf.plugin.v1.InfoResponse
	10, // 29: osctf.plugin.v1.Notification.Subscriptions:output_type -> osctf.plugin.v1.SubscriptionList
	12, // 30: osctf.plugin.v1.Notification.Notify:output_type -> osctf.plugin.v1.NotifyAck
	2,  // 31: osctf.plugin.v1.ChallengeType.Info:output_type -> osctf.plugin.v1.InfoResponse
	14, // 32: osctf.plugin.v1.ChallengeType.ValidateConfig:output_type -> osctf.plugin.v1.ValidateResponse
	16, // 33: osctf.plugin.v1.ChallengeType.CheckFlag:output_type -> osctf.plugin.v1.CheckResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
